server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/cm_database
    username: cmdatabase
    password: 27041227
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

  main:
    web-application-type: servlet
