name: CI - Build Backend

on:
  pull_request:
    branches:
      - "main"
    paths:
      - cm-backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    services: # [1] Start postgres container
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: cmdatabase
          POSTGRES_PASSWORD: 27041227
          POSTGRES_DB: cm_database
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./cm-backend
    steps:
      - uses: actions/checkout@v4 # [2] checkout/clone the repository
      - uses: actions/setup-java@v3 # [3] setup java
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests in maven # [4] build and run unit/integration tests
        run: mvn -ntp -B verify