name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cm-backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: cmdatabase
          POSTGRES_PASSWORD: 27041227
          POSTGRES_DB: cm_database
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # set working directory
    defaults:
      run:
        working-directory: cm-backend
    steps:
      - name: Send Slack Message # [1]
        id: slack_deployment_started
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":loading: Deployment started"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/checkout@v4 # [2] checkout/clone repo
      - uses: actions/setup-java@v3 # [3] setup java
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v3 # [4] login to docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set build number # [5] generate build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Send Slack Message # [5]
        id: slack_building_maven
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":maven: Building with maven"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Build Package Push with maven # [6] maven verify (run unit/integration test, build, and oush the image to docker hub)
        run: mvn -ntp -B verify -D docker.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build
      - name: Send Slack Message # [7]
        id: slack_docker_image_pushed_to_dockerhub
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":docker: Image tag:${{steps.build-number.outputs.BUILD_NUMBER}} pushed to https://hub.docker.com/repository/docker/ljcaliwan/cm-backend-api"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update Dockerrun.aws.json api image tag with new build number # [8] Update Dockerrun.aws.json in EB
        run: |
          echo "Dockerrun.aws.json before updating tag"
          cat Dockerrun.aws.json
          sed -i -E 's_(ljcaliwan/cm-backend-api:)([^"]*)_\1'${{steps.build-number.outputs.BUILD_NUMBER}}'_' Dockerrun.aws.json
          echo "Dockerrun.aws.json after updating tag"
          cat Dockerrun.aws.json
      - name: Send Slack Message # [9]
        id: slack-eb-deployment
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":aws: Starting deployment to Elastic Beanstalk"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Deploy to Elastic Beanstalk # [10] Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.SHA }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: cm-backend/Dockerrun.aws.json
      - name: Send Slack Message # [11]
        id: slack-committing-to-repository
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":githubloading: Committing to repository https://github.com/ljcaliwan/cm-app"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Commit and push Dockerrun.aws.json # [12]
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerrun.aws.json image with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push
      - name: Send Slack Message # [13]
        id: slack-deployment-and-commit-to-repository-completed
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":github_check_mark: Deployment and commit to repository completed - http://cm-backend-api-env.eba-bm7jp3mf.ap-southeast-1.elasticbeanstalk.com/"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack Message # [14]
        id: slack-job-status
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":github_check_mark: Job status: ${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
